# netlify.toml

[build]
  # This tells Netlify where your serverless functions are
  functions = "netlify/functions"

[dev]
  # Tell Netlify that your Vite server runs on port 3000
  targetPort = 3000

[build.processing.secrets]
  # Tell the scanner to ignore VITE_MAPS_API_KEY
  # This is safe because this key is restricted to your domain
  ignore_files = ["dist/assets/index-*.js"]