# netlify.toml

[build]
  functions = "netlify/functions"

[dev]
  targetPort = 3000

# This block tells the scanner to allow the *value* of the
# VITE_MAPS_API_KEY environment variable to be public.
[build.processing.secrets]
  smart_detection_omitted_values = ["VITE_MAPS_API_KEY"]